# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: measure.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'measure.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmeasure.proto\x12\rfitme.algo.v1\"\x07\n\x05\x45mpty\")\n\x08PhotoRef\x12\x0c\n\x04view\x18\x01 \x01(\t\x12\x0f\n\x07oss_key\x18\x02 \x01(\t\"\xae\x01\n\x0eMeasureRequest\x12\x0f\n\x07job_uid\x18\x01 \x01(\t\x12%\n\x06gender\x18\x02 \x01(\x0e\x32\x15.fitme.algo.v1.Gender\x12\x11\n\theight_cm\x18\x03 \x01(\x02\x12\x11\n\tweight_kg\x18\x04 \x01(\x02\x12\'\n\x06photos\x18\x05 \x03(\x0b\x32\x17.fitme.algo.v1.PhotoRef\x12\x15\n\rprovider_hint\x18\x06 \x01(\t\"\xbf\x02\n\x0fMeasureResponse\x12\x46\n\x0cmeasurements\x18\x01 \x03(\x0b\x32\x30.fitme.algo.v1.MeasureResponse.MeasurementsEntry\x12\x42\n\nconfidence\x18\x02 \x03(\x0b\x32..fitme.algo.v1.MeasureResponse.ConfidenceEntry\x12\x10\n\x08mesh_key\x18\x03 \x01(\t\x12\x15\n\rprovider_code\x18\x04 \x01(\t\x12\x0f\n\x07\x63ost_ms\x18\x05 \x01(\x05\x1a\x33\n\x11MeasurementsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x1a\x31\n\x0f\x43onfidenceEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"@\n\x0eProviderHealth\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07healthy\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t*D\n\x06Gender\x12\x16\n\x12GENDER_UNSPECIFIED\x10\x00\x12\x0f\n\x0bGENDER_MALE\x10\x01\x12\x11\n\rGENDER_FEMALE\x10\x02\x32\xa4\x01\n\x0eMeasureService\x12H\n\x07Measure\x12\x1d.fitme.algo.v1.MeasureRequest\x1a\x1e.fitme.algo.v1.MeasureResponse\x12H\n\x11GetProviderHealth\x12\x14.fitme.algo.v1.Empty\x1a\x1d.fitme.algo.v1.ProviderHealthBWZUgithub.com/taoyang1223/Xingcai/services/server/internal/shared/pb/measurev1;measurev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'measure_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZUgithub.com/taoyang1223/Xingcai/services/server/internal/shared/pb/measurev1;measurev1'
  _globals['_MEASURERESPONSE_MEASUREMENTSENTRY']._loaded_options = None
  _globals['_MEASURERESPONSE_MEASUREMENTSENTRY']._serialized_options = b'8\001'
  _globals['_MEASURERESPONSE_CONFIDENCEENTRY']._loaded_options = None
  _globals['_MEASURERESPONSE_CONFIDENCEENTRY']._serialized_options = b'8\001'
  _globals['_GENDER']._serialized_start=649
  _globals['_GENDER']._serialized_end=717
  _globals['_EMPTY']._serialized_start=32
  _globals['_EMPTY']._serialized_end=39
  _globals['_PHOTOREF']._serialized_start=41
  _globals['_PHOTOREF']._serialized_end=82
  _globals['_MEASUREREQUEST']._serialized_start=85
  _globals['_MEASUREREQUEST']._serialized_end=259
  _globals['_MEASURERESPONSE']._serialized_start=262
  _globals['_MEASURERESPONSE']._serialized_end=581
  _globals['_MEASURERESPONSE_MEASUREMENTSENTRY']._serialized_start=479
  _globals['_MEASURERESPONSE_MEASUREMENTSENTRY']._serialized_end=530
  _globals['_MEASURERESPONSE_CONFIDENCEENTRY']._serialized_start=532
  _globals['_MEASURERESPONSE_CONFIDENCEENTRY']._serialized_end=581
  _globals['_PROVIDERHEALTH']._serialized_start=583
  _globals['_PROVIDERHEALTH']._serialized_end=647
  _globals['_MEASURESERVICE']._serialized_start=720
  _globals['_MEASURESERVICE']._serialized_end=884
# @@protoc_insertion_point(module_scope)
