# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import measure_pb2 as measure__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in measure_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MeasureServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Measure = channel.unary_unary(
                '/fitme.algo.v1.MeasureService/Measure',
                request_serializer=measure__pb2.MeasureRequest.SerializeToString,
                response_deserializer=measure__pb2.MeasureResponse.FromString,
                _registered_method=True)
        self.GetProviderHealth = channel.unary_unary(
                '/fitme.algo.v1.MeasureService/GetProviderHealth',
                request_serializer=measure__pb2.Empty.SerializeToString,
                response_deserializer=measure__pb2.ProviderHealth.FromString,
                _registered_method=True)


class MeasureServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Measure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProviderHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MeasureServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Measure': grpc.unary_unary_rpc_method_handler(
                    servicer.Measure,
                    request_deserializer=measure__pb2.MeasureRequest.FromString,
                    response_serializer=measure__pb2.MeasureResponse.SerializeToString,
            ),
            'GetProviderHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProviderHealth,
                    request_deserializer=measure__pb2.Empty.FromString,
                    response_serializer=measure__pb2.ProviderHealth.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fitme.algo.v1.MeasureService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fitme.algo.v1.MeasureService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MeasureService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Measure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fitme.algo.v1.MeasureService/Measure',
            measure__pb2.MeasureRequest.SerializeToString,
            measure__pb2.MeasureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProviderHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fitme.algo.v1.MeasureService/GetProviderHealth',
            measure__pb2.Empty.SerializeToString,
            measure__pb2.ProviderHealth.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
