# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ocr.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'ocr.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tocr.proto\x12\rfitme.algo.v1\"\x1b\n\x08ImageRef\x12\x0f\n\x07oss_key\x18\x01 \x01(\t\">\n\tTableCell\x12\x0e\n\x06header\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\"G\n\x08TableRow\x12\x12\n\nsize_label\x18\x01 \x01(\t\x12\'\n\x05\x63\x65lls\x18\x02 \x03(\x0b\x32\x18.fitme.algo.v1.TableCell\"o\n\x0bTableResult\x12%\n\x04rows\x18\x01 \x03(\x0b\x32\x17.fitme.algo.v1.TableRow\x12\x14\n\x0cmeasure_mode\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\x0f\n\x07message\x18\x04 \x01(\t2S\n\nOcrService\x12\x45\n\x0eParseSizeChart\x12\x17.fitme.algo.v1.ImageRef\x1a\x1a.fitme.algo.v1.TableResultBOZMgithub.com/taoyang1223/Xingcai/services/server/internal/shared/pb/ocrv1;ocrv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ocr_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZMgithub.com/taoyang1223/Xingcai/services/server/internal/shared/pb/ocrv1;ocrv1'
  _globals['_IMAGEREF']._serialized_start=28
  _globals['_IMAGEREF']._serialized_end=55
  _globals['_TABLECELL']._serialized_start=57
  _globals['_TABLECELL']._serialized_end=119
  _globals['_TABLEROW']._serialized_start=121
  _globals['_TABLEROW']._serialized_end=192
  _globals['_TABLERESULT']._serialized_start=194
  _globals['_TABLERESULT']._serialized_end=305
  _globals['_OCRSERVICE']._serialized_start=307
  _globals['_OCRSERVICE']._serialized_end=390
# @@protoc_insertion_point(module_scope)
