# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import render_pb2 as render__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in render_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RenderServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RenderTryOn = channel.unary_unary(
                '/fitme.algo.v1.RenderService/RenderTryOn',
                request_serializer=render__pb2.TryOnRequest.SerializeToString,
                response_deserializer=render__pb2.ImageResult.FromString,
                _registered_method=True)


class RenderServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RenderTryOn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RenderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RenderTryOn': grpc.unary_unary_rpc_method_handler(
                    servicer.RenderTryOn,
                    request_deserializer=render__pb2.TryOnRequest.FromString,
                    response_serializer=render__pb2.ImageResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fitme.algo.v1.RenderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fitme.algo.v1.RenderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RenderService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RenderTryOn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fitme.algo.v1.RenderService/RenderTryOn',
            render__pb2.TryOnRequest.SerializeToString,
            render__pb2.ImageResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
