# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: render.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'render.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0crender.proto\x12\rfitme.algo.v1\"L\n\x0cTryOnRequest\x12\x13\n\x0bprofile_uid\x18\x01 \x01(\t\x12\x13\n\x0bproduct_uid\x18\x02 \x01(\t\x12\x12\n\nsize_label\x18\x03 \x01(\t\"1\n\x0bImageResult\x12\x11\n\timage_key\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2W\n\rRenderService\x12\x46\n\x0bRenderTryOn\x12\x1b.fitme.algo.v1.TryOnRequest\x1a\x1a.fitme.algo.v1.ImageResultBUZSgithub.com/taoyang1223/Xingcai/services/server/internal/shared/pb/renderv1;renderv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'render_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZSgithub.com/taoyang1223/Xingcai/services/server/internal/shared/pb/renderv1;renderv1'
  _globals['_TRYONREQUEST']._serialized_start=31
  _globals['_TRYONREQUEST']._serialized_end=107
  _globals['_IMAGERESULT']._serialized_start=109
  _globals['_IMAGERESULT']._serialized_end=158
  _globals['_RENDERSERVICE']._serialized_start=160
  _globals['_RENDERSERVICE']._serialized_end=247
# @@protoc_insertion_point(module_scope)
