// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: measure.proto

package measurev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MeasureService_Measure_FullMethodName           = "/fitme.algo.v1.MeasureService/Measure"
	MeasureService_GetProviderHealth_FullMethodName = "/fitme.algo.v1.MeasureService/GetProviderHealth"
)

// MeasureServiceClient is the client API for MeasureService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MeasureServiceClient interface {
	Measure(ctx context.Context, in *MeasureRequest, opts ...grpc.CallOption) (*MeasureResponse, error)
	GetProviderHealth(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProviderHealth, error)
}

type measureServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMeasureServiceClient(cc grpc.ClientConnInterface) MeasureServiceClient {
	return &measureServiceClient{cc}
}

func (c *measureServiceClient) Measure(ctx context.Context, in *MeasureRequest, opts ...grpc.CallOption) (*MeasureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MeasureResponse)
	err := c.cc.Invoke(ctx, MeasureService_Measure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *measureServiceClient) GetProviderHealth(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProviderHealth, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProviderHealth)
	err := c.cc.Invoke(ctx, MeasureService_GetProviderHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MeasureServiceServer is the server API for MeasureService service.
// All implementations must embed UnimplementedMeasureServiceServer
// for forward compatibility.
type MeasureServiceServer interface {
	Measure(context.Context, *MeasureRequest) (*MeasureResponse, error)
	GetProviderHealth(context.Context, *Empty) (*ProviderHealth, error)
	mustEmbedUnimplementedMeasureServiceServer()
}

// UnimplementedMeasureServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMeasureServiceServer struct{}

func (UnimplementedMeasureServiceServer) Measure(context.Context, *MeasureRequest) (*MeasureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Measure not implemented")
}
func (UnimplementedMeasureServiceServer) GetProviderHealth(context.Context, *Empty) (*ProviderHealth, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProviderHealth not implemented")
}
func (UnimplementedMeasureServiceServer) mustEmbedUnimplementedMeasureServiceServer() {}
func (UnimplementedMeasureServiceServer) testEmbeddedByValue()                        {}

// UnsafeMeasureServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MeasureServiceServer will
// result in compilation errors.
type UnsafeMeasureServiceServer interface {
	mustEmbedUnimplementedMeasureServiceServer()
}

func RegisterMeasureServiceServer(s grpc.ServiceRegistrar, srv MeasureServiceServer) {
	// If the following call pancis, it indicates UnimplementedMeasureServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MeasureService_ServiceDesc, srv)
}

func _MeasureService_Measure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MeasureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeasureServiceServer).Measure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeasureService_Measure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeasureServiceServer).Measure(ctx, req.(*MeasureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeasureService_GetProviderHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeasureServiceServer).GetProviderHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeasureService_GetProviderHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeasureServiceServer).GetProviderHealth(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// MeasureService_ServiceDesc is the grpc.ServiceDesc for MeasureService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MeasureService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fitme.algo.v1.MeasureService",
	HandlerType: (*MeasureServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Measure",
			Handler:    _MeasureService_Measure_Handler,
		},
		{
			MethodName: "GetProviderHealth",
			Handler:    _MeasureService_GetProviderHealth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "measure.proto",
}
