// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: render.proto

package renderv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RenderService_RenderTryOn_FullMethodName = "/fitme.algo.v1.RenderService/RenderTryOn"
)

// RenderServiceClient is the client API for RenderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RenderServiceClient interface {
	RenderTryOn(ctx context.Context, in *TryOnRequest, opts ...grpc.CallOption) (*ImageResult, error)
}

type renderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRenderServiceClient(cc grpc.ClientConnInterface) RenderServiceClient {
	return &renderServiceClient{cc}
}

func (c *renderServiceClient) RenderTryOn(ctx context.Context, in *TryOnRequest, opts ...grpc.CallOption) (*ImageResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImageResult)
	err := c.cc.Invoke(ctx, RenderService_RenderTryOn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RenderServiceServer is the server API for RenderService service.
// All implementations must embed UnimplementedRenderServiceServer
// for forward compatibility.
type RenderServiceServer interface {
	RenderTryOn(context.Context, *TryOnRequest) (*ImageResult, error)
	mustEmbedUnimplementedRenderServiceServer()
}

// UnimplementedRenderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRenderServiceServer struct{}

func (UnimplementedRenderServiceServer) RenderTryOn(context.Context, *TryOnRequest) (*ImageResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenderTryOn not implemented")
}
func (UnimplementedRenderServiceServer) mustEmbedUnimplementedRenderServiceServer() {}
func (UnimplementedRenderServiceServer) testEmbeddedByValue()                       {}

// UnsafeRenderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RenderServiceServer will
// result in compilation errors.
type UnsafeRenderServiceServer interface {
	mustEmbedUnimplementedRenderServiceServer()
}

func RegisterRenderServiceServer(s grpc.ServiceRegistrar, srv RenderServiceServer) {
	// If the following call pancis, it indicates UnimplementedRenderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RenderService_ServiceDesc, srv)
}

func _RenderService_RenderTryOn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TryOnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RenderServiceServer).RenderTryOn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RenderService_RenderTryOn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RenderServiceServer).RenderTryOn(ctx, req.(*TryOnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RenderService_ServiceDesc is the grpc.ServiceDesc for RenderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RenderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fitme.algo.v1.RenderService",
	HandlerType: (*RenderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RenderTryOn",
			Handler:    _RenderService_RenderTryOn_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "render.proto",
}
